// Auth Types
export const LOGIN = 'LOGIN';
export const CHILD_LOGIN = 'CHILD_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// Exams Types
export const EXAMS = 'EXAMS';
export const ADD_EXAM_TYPE_SUCCESS = 'ADD_EXAM_TYPE_SUCCESS';
export const ADD_EXAM_TYPE_FAILURE = 'ADD_EXAM_TYPE_FAILURE';
export const GET_ALL_EXAM_TYPES = 'GET_ALL_EXAM_TYPES';
export const CLEAR_EXAM_TYPES_ERRORS = 'CLEAR_EXAM_TYPES_ERRORS';
export const FILTERED_EXAMS = 'FILTERED_EXAMS';
export const ADD_EXAMS_FAILURE = 'ADD_EXAMS_FAILURE';
export const GET_STD_TO_ADD_EDIT_EXAM_MARKS = 'GET_STD_TO_ADD_EDIT_EXAM_MARKS';
export const STUDENTS_TO_ADD_EDIT_MARKS = 'STUDENTS_TO_ADD_EDIT_MARKS';
export const STUDENTS_EXAMS_RESULT = 'STUDENTS_EXAMS_RESULT';

// Leave Types
export const LEAVES = 'LEAVES';
export const LEAVE_TYPES = 'LEAVE_TYPES';
export const APPLY_LEAVES = 'APPLY_LEAVES';
export const FILTERED_LEAVES = 'FILTERED_LEAVES';
export const CLEAR_LEAVES = 'CLEAR_LEAVES';

// Curriculum Types
export const CURRICULUM_LIST = 'CURRICULUM_LIST';
export const SHOW_CURRICULUM = 'SHOW_CURRICULUM';
export const ADD_CURRICULUM = 'ADD_CURRICULUM';
export const TEACHER_CLASSES = 'TEACHER_CLASSES';
export const SUBJECTS_GRADES = 'SUBJECTS_GRADES';
export const MAIN_HEADING = 'MAIN_HEADING';
export const SUB_HEADING = 'SUB_HEADING';

// Organization Types
export const FIND_ORGANIZATION = 'FIND_ORGANIZATION';
export const CURRENT_ORGANIZATION = 'CURRENT_ORGANIZATION';
export const CLEAR_ORGANIZATION = 'CLEAR_ORGANIZATION';

// Teacher Types
export const GET_TEACHER_CLASSES = 'GET_TEACHER_CLASSES';
export const CLASS_SUBJECTS = 'CLASS_SUBJECTS';

// Attendence Types
export const CLASS_TEACHER_CLASSES = 'CLASS_TEACHER_CLASSES';
export const SHOW_ATTENDENCE = 'SHOW_ATTENDENCE';
export const SHOW_ATTENDENCE_ERROR = 'SHOW_ATTENDENCE_ERROR';
export const STD_ATTENDENCE = 'STD_ATTENDENCE';
export const STORE_ATTENDENCE_SUCCESS = 'STORE_ATTENDENCE_SUCCESS';
export const CLEAR_ATTENDENCE_ERRORS = 'CLEAR_ATTENDENCE_ERRORS';

// Common Types
export const IS_LOADING = 'IS_LOADING';
export const CLEAR_LOADING_STATE = 'CLEAR_LOADING_STATE';
export const USER_PROFILE = 'USER_PROFILE';
export const TIMETABLE = 'TIMETABLE';
export const DASHBOARD = 'DASHBOARD';

// Exam Report
export const CLASS_STUDENTS = 'CLASS_STUDENTS';
export const SELECT_ALL_STDS = 'SELECT_ALL_STDS';
export const UNSELECT_ALL_STDS = 'UNSELECT_ALL_STDS';
export const SELECT_SPECIFIC_STDS = 'SELECT_SPECIFIC_STDS';
export const UNSELECT_SPECIFIC_STDS = 'UNSELECT_SPECIFIC_STDS';

// App Mode
export const APP_MODE = 'APP_MODE';

// Assignment Types
export const ALL_ASSIGNMENTS = 'ALL_ASSIGNMENTS';
export const ADD_ASSIGNMENT_SUCCESS = 'ADD_ASSIGNMENT_SUCCESS';
export const ADD_ASSIGNMENT_FAILURE = 'ADD_ASSIGNMENT_FAILURE';
export const FILTERED_ASSIGNMENTS = 'FILTERED_ASSIGNMENTS';
export const STUDENTS_TO_ADD_EDIT_ASSIGNMENT_MARKS =
  'STUDENTS_TO_ADD_EDIT_ASSIGNMENT_MARKS';
